services:
  view-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL
        - VITE_MEDIA_API_URL
    expose:
      - '80'
    container_name: greact-drill-view-${BRANCH}
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_MEDIA_API_URL=${VITE_MEDIA_API_URL}
    networks:
      - proxy

networks:
  proxy:
    external: true