version: '3.7'
name: 'drill-cloud-frontend'

services:
  app:
    image: cloud-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL
        - VITE_MEDIA_API_URL
    ports:
      - '4000:4000'
    volumes:
      - cloud-frontend:/cloud-frontend
    networks:
      - cloud-backend

volumes:
  cloud-frontend:

networks:
  cloud-backend:
    driver: bridge
